# Ingress creation
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: votingapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/issuer: letsencrypt
    cert-manager.io/issuer-kind: Issuer
    cert-manager.io/issuer-group: cert-manager.io
spec:
  ingressClassName: nginx-prod
  rules:
  - host: smoothie-prod.simplon-duna.space
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vote-service
            port: 
              number: 80
  tls: # placing a host in the TLS config will determine what ends up in the cert's subjectAlt
  - hosts:
    - smoothie-prod.simplon-duna.space
    secretName: secret-tls # cert-manager will store the created certificate in this secret.